name: fnrco_candidates
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  concentric_transition: ^1.0.3
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  dio2: ^5.0.0-nullsafety
  flutter_secure_storage: ^9.2.2
  #pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  in_app_review: ^2.0.9
  #syncfusion_flutter_pdfviewer: ^27.1.52
  flutter_downloader: ^1.11.8
  #device_info_plus: ^10.1.2
  flutter_pdfview: ^1.3.3
  permission_handler: ^11.3.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  rename: ^3.0.2
  package_info_plus: ^8.1.0
  local_auth: ^2.3.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.0
  toastification: ^2.3.0
  lottie: ^3.1.3
  logger: ^2.4.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  google_sign_in: ^6.2.2
  linkedin_login: ^3.0.5
  flutter_facebook_auth: ^7.1.1
  flutter_widget_from_html: ^0.15.3
  redacted: ^1.0.12
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.4.1
  stylish_bottom_bar: ^1.1.0
  file_picker: 8.1.3
  dropdown_search: ^6.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter_native_splash:
  android: true
  ios: true
  web: false
  icon_background_color: "#111111"
  color: "#ae1f23"
  image: assets/images/splash.png
  android_12:
    color: "#ae1f23"
    image: assets/images/splash.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/youtube.png
    - assets/bottom/
    - assets/svg/
    - assets/lottie/
    - lang/ar.json
    - lang/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
